### ISSUE TITLE
Should this be >=5 to support DCASE 2017 Task 3 annotation format?

### ISSUE THREAD

**Issue by alexdiment** [TUT-ARG/sed_vis#1]
https://github.com/TUT-ARG/sed_vis/blob/9f8bf8fcbdd411fb10dd06a0f6d001d879c83fdb/sed_vis/io.py#L194

**Comment by toni-heittola** [comment]
io-tools are now removed as the `dcase_util` package provides more robust meta data reader. 

Usage example:
```
import dcase_util
event_list = dcase_util.containers.MetaDataContainer().load('event_list.txt')
```

**Comment by icestoneking** [comment]
sed_visualizer
========================================
  Audio file                        : ./tests/data/a001.wav 
  Event lists
    ID   Label          Event list file                        
    --   ------------   -------------------------------------  
    0    reference      ./tests/data/a001.ann                  
    1    system         ./tests/data/a001_system_output.ann    

  Mode                              : None 
  Active events                     : None 
  Publication mode                  : False 
  minimum event length              : None 
  minimum event gap                 : None 
========================================
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Colormap spectral is not recognized. Possible values are: Accent, Accent_r, Blues, Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap, CMRmap_r, Dark2, Dark2_r, GnBu, GnBu_r, Greens, Greens_r, Greys, Greys_r, OrRd, OrRd_r, Oranges, Oranges_r, PRGn, PRGn_r, Paired, Paired_r, Pastel1, Pastel1_r, Pastel2, Pastel2_r, PiYG, PiYG_r, PuBu, PuBuGn, PuBuGn_r, PuBu_r, PuOr, PuOr_r, PuRd, PuRd_r, Purples, Purples_r, RdBu, RdBu_r, RdGy, RdGy_r, RdPu, RdPu_r, RdYlBu, RdYlBu_r, RdYlGn, RdYlGn_r, Reds, Reds_r, Set1, Set1_r, Set2, Set2_r, Set3, Set3_r, Spectral, Spectral_r, Wistia, Wistia_r, YlGn, YlGnBu, YlGnBu_r, YlGn_r, YlOrBr, YlOrBr_r, YlOrRd, YlOrRd_r, afmhot, afmhot_r, autumn, autumn_r, binary, binary_r, bone, bone_r, brg, brg_r, bwr, bwr_r, cividis, cividis_r, cool, cool_r, coolwarm, coolwarm_r, copper, copper_r, cubehelix, cubehelix_r, flag, flag_r, gist_earth, gist_earth_r, gist_gray, gist_gray_r, gist_heat, gist_heat_r, gist_ncar, gist_ncar_r, gist_rainbow, gist_rainbow_r, gist_stern, gist_stern_r, gist_yarg, gist_yarg_r, gnuplot, gnuplot2, gnuplot2_r, gnuplot_r, gray, gray_r, hot, hot_r, hsv, hsv_r, inferno, inferno_r, jet, jet_r, magma, magma_r, nipy_spectral, nipy_spectral_r, ocean, ocean_r, pink, pink_r, plasma, plasma_r, prism, prism_r, rainbow, rainbow_r, seismic, seismic_r, spring, spring_r, summer, summer_r, tab10, tab10_r, tab20, tab20_r, tab20b, tab20b_r, tab20c, tab20c_r, terrain, terrain_r, viridis, viridis_r, winter, winter_r

**Comment by toni-heittola** [comment]
This error is related to matplotlib, what version you are using?

**Comment by icestoneking** [comment]
Using /usr/local/lib/python2.7/dist-packages/PyAudio-0.2.11-py2.7-linux-x86_64.egg
Searching for matplotlib==2.2.0
Best match: matplotlib 2.2.0
Adding matplotlib 2.2.0 to easy-install.pth file
