### ISSUE TITLE
Visualizer with probability

### ISSUE THREAD

**Issue by JingpengSun** [TUT-ARG/sed_vis#4]
Hi, when I run the 
Quickstart: Using sed_vis in Python code
with the demo file a001.wav and a001_system_output_prob.csv
that is:

import sed_vis
import dcase_util
audio_container = dcase_util.containers.AudioContainer().load(
    './tests/data/a001.wav'
)
reference_event_list = dcase_util.containers.MetaDataContainer().load(
    './tests/data/a001.ann'
)
estimated_event_list = dcase_util.containers.MetaDataContainer().load(
    './tests/data/a001_system_output_prob.csv'
)
event_lists = {
    'reference': reference_event_list, 
    'estimated': estimated_event_list
}
vis = sed_vis.visualization.EventListVisualizer(event_lists=event_lists,
                                                audio_signal=audio_container.data,
                                                sampling_rate=audio_container.fs)
vis.show()

However, I got the following warning:
.../lib/python2.7/site-packages/matplotlib/figure.py:2299: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "
.../lib/python2.7/site-packages/matplotlib/tight_layout.py:209: UserWarning: tight_layout cannot make axes height small enough to accommodate all axes decorations
  warnings.warn('tight_layout cannot make axes height small enough '

and the resulted png figure didn't show probability and the estimated results were also gone.

I don't know how to figure it out, can you give me some tips? Thank you very much!

**Comment by toni-heittola** [comment]
I cannot reproduce this issue with Python 3.6 and matplotlib 2.2.3.
What version of matplotlib you are using? Seems that you are using Python 2.7.

**Comment by JingpengSun** [comment]
Thank you for your prompt reply. 
Yes, I am using Python2.7 in order to use this repo directly. And the version of matplotlib is 2.2.4.
So, can we do something to make it work?

**Comment by toni-heittola** [comment]
Unfortunately, it seems that I cannot reproduce this issue even with matching matplotlib version. I get correct png-file when using `vis.save(filename='test.png')` instead of `vis.show()`.

**Comment by JingpengSun** [comment]
Ok, thank you~ I will take more tries~ I close it.
