### ISSUE TITLE
IOError: [Errno -9996] Invalid output device (no default output device)

### ISSUE THREAD

**Issue by JingpengSun** [TUT-ARG/sed_vis#6]
Hello, I get a figure with 'play', 'stop' and 'close' tag, after run sed_visualizer.py as supposed.
I want to listen to the audio by click the 'play' tag,
however, I get a error:
IOError: [Errno -9996] Invalid output device (no default output device)
as shown in the title

I google it, and find that maybe something wrong with pyaudio and portaudio
I try to fix it follow the two methods in the following :
https://stackoverflow.com/questions/4672155/pyaudio-ioerror-no-default-input-device-available?rq=1

unfortunately, they fail to fix it.

Do you have met this? any advice would be appreciated!

**Comment by JingpengSun** [comment]
I found it works well on a Windows computer while fail to perform on another Ubantu one, maybe there something wrong with my Unbantu computer.
anyway, it works.
And I'd like to consult you a few questions,if you don't mind.
In the left bottom of the visualizer GUI, there are serval functional buttons, two of them are "Back to previous view" and "Forward to next view".
I want to know where I can find the soure code which defines them.
Many thanks~

**Comment by toni-heittola** [comment]
Top toolbar is not created by `sed_vis`, it is a default toolbar created by matplotlib library used to make visualizations. There is a way to hide the toolbar by adjusting matplotlib settings if needed.

Unfortunately, I do not have any advice for the IOError you encountered. I have used pyaudio without any problem in different Ubuntu and CentOS installations so far.
